#!/usr/bin/env bash
cc -o crypto crypto.c -DMAIN
cc -o keygen keygen.c
cc -c crypto.c
cc -o otp_enc otp_enc.c
cc -o otp_enc_d otp_enc_d.c crypto.o
cc -o otp_dec otp_dec.c
cc -o otp_dec_d otp_dec_d.c crypto.o
